### ISSUE TITLE
Support for Springboot 2.x and Java 10

### ISSUE THREAD

**Issue by DarkStar1** [holon-platform/holon-jaxrs#34]
Currently it is not possible to create any holon-* based project with springboot 2 (in my case 2.0.3-RELEASE) with a JDK 9/10 target.
I see that there's a 5.2.x (as labelled in the branches) release in the pipeline.
Any chance/news on when to be expecting a compatible release?
Or if there's an interim solution to the [RelaxedPropertyResolver](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#externalized-configuration) issue, I'd be greatful for any information on how to implement it.

**Comment by rrighi** [comment]
Hi @DarkStar1,
Actually the Spring Boot 2 support is foreseen for the **5.2.0 platform release**, which will include:

- Support for JDK 9+
- Support for Spring 5.x
- Support for Spring Boot 2.x
- Full support for JAX-RS 2.1
- Support for Swagger/OpenAPI 3
- Support for async and reactive programming (including _RxJava_ and _Project Reactor_ integration)
- A new MongoDB `Datastore`
- Support for Vaadin Flow (version 10+)
- Many API enhancements and new features 

The Holon Platform version 5.2.0 is expected to be stable and will be published within the end of September 2018.

But we are planning to pusblish an **alpha version** which will include only:
- Support for JDK 9+
- Support for Spring 5.x
- Support for Spring Boot 2.x
- Full support for JAX-RS 2.1

This alpha version will be almost surely available **within the end of the next week**. So I suggest you wait for this version for Spring Boot 2.x full support.

Check GitHub and the [Holon Platform website](https://holon-platform.com) for the announcements.
If you have any further questions, please don't hesitate to ask.

**Comment by DarkStar1** [comment]
Thank you very much. For the time being I'll try another solution and upgrade to your platform solution when the alpha comes out.

**Comment by rrighi** [comment]
Hi @DarkStar1,
the Holon Platform [5.2.0-alpha1 release](https://github.com/holon-platform/platform/releases/tag/5.2.0-alpha1) is now available for download.
See the [release announcement blog post](https://holon-platform.com/release-announcements/holon-5-2-alpha-release/) for details.

Please let me know if something don't work as expected!

**Comment by DarkStar1** [comment]
Thanks. I tried it out and seems to work fine now. I'll update you as I continue to use it.
An almost unrelated question; are there any plans to include the swagger UI in the future?

**Comment by rrighi** [comment]
We are thinking to include the Swagger UI, but we don't have specific plans by now. We surely evaluate this, most likely after the stable 5.2.0 platform release. 
Check the blog for updates, any suggestion is always welcome!
